[env]
PROJECT_NAME = "iml-official"
ENV = ".env.local"
DOCKER_COMPOSE_LOCAL = "client/docker-compose.yaml"

[tasks.down]
script_runner = "@shell"
script = '''
docker compose -p "${PROJECT_NAME}" down --rmi all --volumes --remove-orphans
'''

[tasks.up]
dependencies = ["down"]
script_runner = "@shell"
script = '''
docker compose -p "${PROJECT_NAME}" -f "${DOCKER_COMPOSE_LOCAL}" up -d
'''
